services:
  crm-app:
    build: .
    container_name: crm-backend
    restart: on-failure
    environment:

      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: ${KC_EXTERNAL_URL}/realms/crm-realm
      SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: ${KC_INTERNAL_URL}/realms/crm-realm/protocol/openid-connect/certs


      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}

      KEYCLOAK_REALM: crm-realm
      KEYCLOAK_CLIENT_ID: crm-backend
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET}


      KEYCLOAK_AUTH_SERVER_URL: http://keycloak:8080

      CAKTO_WEBHOOK_SECRET: ${CAKTO_WEBHOOK_SECRET}
      CAKTO_PRODUCT_ID: ${CAKTO_PRODUCT_ID}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}
    ports:
      - "2000:2000"
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started
    networks:
      - crm-network

  postgres:
    image: postgres:16
    container_name: crm-postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "2001:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - crm-network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: crm-auth
    restart: always
    command: start-dev
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: ${KC_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD}
      KC_HOSTNAME: ${KC_EXTERNAL_URL}
      KC_HOSTNAME_STRICT: "false"
      KC_HTTP_ENABLED: "true"
      KC_PROXY: edge
    ports:
      - "2002:8080"
    depends_on:
      - postgres
    networks:
      - crm-network

  adminer:
    image: adminer
    container_name: crm-adminer
    restart: always
    ports:
      - "2003:8080"
    depends_on:
      - postgres
    networks:
      - crm-network

networks:
  crm-network:
    driver: bridge

volumes:
  postgres_data: